config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'shindan1', to: 'questions#shindan1'
  get 'shindan2', to: 'questions#shindan2'
  get 'shindan3', to: 'questions#shindan3'
  get 'shindan4', to: 'questions#shindan4'
  get 'shindan5', to: 'questions#shindan5'
  get 'results', to: 'results#results'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/island.rb
class Island < ApplicationRecord
  has_many :island_tags
  has_many :tags, through: :island_tags
  has_many :spots
  has_one_attached :image
end

app/models/island_tag.rb
class IslandTag < ApplicationRecord
  belongs_to :island
  belongs_to :tag
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :island
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :island_tags
  has_many :islands, through: :island_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def add_answer_to_session
    unless request.query_parameters.blank?
      session[:answer] << params[:tag][:name]
    else
      redirect_to root_path, flash: {primary: '正常に診断できませんでした。もう一度始めからやり直してください。'}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    session[:answer] = []
    session[:answer].clear if session[:answer] != nil
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :add_answer_to_session, only: %i[shindan2 shindan3 shindan4 shindan5]

  def shindan1; end

  def shindan2; end

  def shindan3; end

  def shindan4; end

  def shindan5; end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :add_answer_to_session

  def results
    if session[:answer].length != 5
      redirect_to root_path, flash: {primary: '正常に診断できませんでした。もう一度始めからやり直してください。'}
    end
    @islands = Island.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'シマサガシ',
      title: 'シマサガシ あなたにおすすめの「島」を提案するサービス',
      reverse: true,
      separator: '|',
      description: '旅行先を考える際に「島」という選択肢を提案するサービスです。簡単な質問に答えるだけであなたにオススメの島を診断します。',
      keywords: '旅行, 国内, 一人旅, 島',
      canonical: request.original_url,
      noindex: ! Rails.env.production?,
      icon: [
        { href: image_url('favicon.ico') },
        # { href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: 'シマサガシ',
        title: 'あなたにおすすめの「島」を提案するサービス',
        description: '旅行先を考える際に「島」という選択肢を提案するサービスです。簡単な質問に答えるだけであなたにオススメの島を診断します。',
        type: 'website',
        url: request.original_url,
        image: image_url('logos/ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@tanakadessssu',
      }
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/home/top.html.slim
.content-wrapper
  .error-message
    - if flash[:primary]
      p.alert.alert-primary
        = flash[:primary]
  .container
    = image_tag 'logos/logo-mark.png', class: 'logo-mark', alt: 'シマサガシロゴマーク画像'
    = image_tag 'logos/logo-name-white.png', class: 'service-title', alt: 'シマサガシタイトルロゴ画像'
    .content
      = image_tag 'logos/foundation.png', class: 'foundation'
      p
        | 「島」、行ってみたくない？
    = link_to shindan1_path, class: 'btn btn-diagnosis', id: 'btn-diagnosis-top' do
      | 行く
      span.question-mark
        | ？
      span.exclamation-mark
        | ！

app/views/layouts/application.html.slim
doctype html
html lang='ja'
  head
    title
      | シマサガシ
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    / フォント
    link[rel="preconnect" href="https://fonts.googleapis.com"]
    link[rel="preconnect" href="https://fonts.gstatic.com" crossorigin=""]
    link[href="https://fonts.googleapis.com/css2?family=Kosugi&display=swap" rel="stylesheet"]

    = display_meta_tags(default_meta_tags)
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    - if Rails.env.production?
      = render 'shared/google_analytics'
  body
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/questions/shindan1.html.slim
- set_meta_tags noindex: true
.content-wrapper
  .question-wrapper
    .question-card
      .choices
        h3 A:キレイな海に癒されたい
        p
          | or
        h3 B:トレッキングで汗を流したい
      .choice-button-area
        = link_to 'A', shindan2_path(tag: { name: '海' }), class: 'btn btn-a'
        = link_to 'B', shindan2_path(tag: { name: 'トレッキング' }), class: 'btn btn-b'
      .ship-progression
        .ferry-icon
          = image_tag 'icons/ferry_icon.png'
        .wave-icon
          = image_tag 'icons/wave_icon.png'
        .number-icon
          = image_tag 'icons/number_2_icon.png'
        .wave-icon
          = image_tag 'icons/wave_icon.png'
        .number-icon
          = image_tag 'icons/number_3_icon.png'
        .wave-icon
          = image_tag 'icons/wave_icon.png'
        .number-icon
          = image_tag 'icons/number_4_icon.png'
        .wave-icon
          = image_tag 'icons/wave_icon.png'
        .number-icon
          = image_tag 'icons/number_5_icon.png'

app/views/questions/shindan2.html.slim
- set_meta_tags noindex: true
.content-wrapper
  .question-card
    .choices
      h3 A:廃墟を訪れてノスタルジーな気分に浸りたい
      p
        | or
      h3 B:芸術に触れて感性を磨きたい
    .choice-button-area
      = link_to 'A', shindan3_path(tag: { name: '廃墟' }), class: 'btn btn-a'
      = link_to 'B', shindan3_path(tag: { name: '芸術' }), class: 'btn btn-b'
    .ship-progression
      .number-icon
        = image_tag 'icons/number_1_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .ferry-icon
        = image_tag 'icons/ferry_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_3_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_4_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_5_icon.png'

app/views/questions/shindan3.html.slim
- set_meta_tags noindex: true
.content-wrapper
  .question-card
    .choices
      h3 A:のんびりブラブラしたい
      p
        | or
      h3 B:アクティブに動きたい
    .choice-button-area
      = link_to 'A', shindan4_path(tag: { name: 'のんびり' }), class: 'btn btn-a'
      = link_to 'B', shindan4_path(tag: { name: 'アクティブ' }), class: 'btn btn-b'
    .ship-progression
      .number-icon
        = image_tag 'icons/number_1_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_2_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .ferry-icon
        = image_tag 'icons/ferry_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_4_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_5_icon.png'

app/views/questions/shindan4.html.slim
- set_meta_tags noindex: true
.content-wrapper
  .question-card
    .choices
      h3 A:大きい島に行きたい
      p
        | or
      h3 B:狭い島だとテンションが上がる
    .choice-button-area
      = link_to 'A', shindan5_path(tag: { name: '大きい島' }), class: 'btn btn-a'
      = link_to 'B', shindan5_path(tag: { name: '狭い島' }), class: 'btn btn-b'
    .ship-progression
      .number-icon
        = image_tag 'icons/number_1_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_2_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_3_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .ferry-icon
        = image_tag 'icons/ferry_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_5_icon.png'

app/views/questions/shindan5.html.slim
- set_meta_tags noindex: true
.content-wrapper
  .question-card
    .choices
      h3 A:動物と触れ合いたい
      p
        | or
      h3 B:歴史や伝統に興味がある
    .choice-button-area
      = link_to 'A', results_path(tag: { name: '動物' }), class: 'btn btn-a'
      = link_to 'B', results_path(tag: { name: '歴史伝統' }), class: 'btn btn-b'
    .ship-progression
      .number-icon
        = image_tag 'icons/number_1_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_2_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_3_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .number-icon
        = image_tag 'icons/number_4_icon.png'
      .wave-icon
        = image_tag 'icons/wave_icon.png'
      .ferry-icon
        = image_tag 'icons/ferry_icon.png'

app/views/results/index.html.slim
.content_wrapper
  h3.results あなたにおすすめの島は…
  - @islands.shuffle.first(3).each do |island|
    - if (island.tags.pluck(:name) & session[:answer]).count >= 3
      h3
        = island.name
      p
        = island.description
        br
        = island.information
  .retry-button
    = link_to 'もう一度探す', shindan1_path, class: 'btn btn-diagnosis'

app/views/results/results.html.slim
- set_meta_tags noindex: true
.result-wrapper
  h3 あなたにおすすめの島は…
  .result-area
    - count = 0
    - @islands.shuffle.each do |island|
      - if (island.tags.pluck(:name) & session[:answer]).count >= 4
        - count += 1
        .result-display-none
          .result-islands
            .island-image
              - if island.image.attached?
                = image_tag island.image, width: '100%', height: '100%', alt: "#{island.name}の画像"
              - else
                = image_tag 'bg_image.jpeg', width: '100%', height: '100%'
            .island-introduce
              .island-location
                h2.island-name
                  = island.name
                h5.island-prefecture
                  = "(#{island.prefecture})"
              p.island-description
                = island.description
              .island-information
                = link_to island.information, target: :_blank, class: 'btn btn-outline-dark' do
                  span
                    = "#{island.name}info"
                = image_tag 'logos/boy-and-girl-gray.png', class: 'boy-and-girl'
          .map
            #map
              script src="https://maps.googleapis.com/maps/api/js?key=#{ ENV['GOOGLE_MAP_API_KEY'] }&callback=initMap&v=weekly" async=""
              javascript:
                function initMap(){
                  map = new google.maps.Map(document.getElementById('map'), {
                    center: {lat: #{island.latitude}, lng: #{island.longitude}},
                    zoom: 13
                  });
                  marker = new google.maps.Marker({
                    position: {lat: #{island.latitude}, lng: #{island.longitude}},
                    map: map
                  });
                };
        .buttons
          = link_to 'もう一度探す', root_path, class: 'btn btn-diagnosis retry'
          = link_to "https://twitter.com/share?url=https://shimasagashi.herokuapp.com&text=シマサガシで「#{island.name}(#{island.prefecture})」をオススメされました！&hashtags=シマサガシ", class: 'btn btn-primary', target: '_blank' do
            i class="fab fa-twitter"
            |  ツイートする
        - break if count == 1

app/views/shared/_footer.html.slim
.footer
  = link_to '利用規約', '', remote: true, class: 'footer-item js-terms-modal-open'
  .modal.js-terms-modal
    .modal-bg.js-terms-modal-close
      .modal-content
        = render 'shared/terms'
  = link_to 'プライバシーポリシー', '', remote: true, class: 'footer-item js-privacy-policy-modal-open'
  .modal.js-privacy-policy-modal
    .modal-bg.js-privacy-policy-modal-close
      .modal-content
        = render 'shared/privacy_policy'
  = link_to 'お問い合わせ',
            'https://docs.google.com/forms/d/e/1FAIpQLSeDRKK13Q8fHzjLXKOKmDYy2vQ1NbXHDyaLEOntLl0_U9UzEw/viewform?usp=sf_link',
            target: :_blank,
            rel: 'noopener noreferrer',
            class: 'footer-item'
  .copyright
    | ©︎2021 シマサガシ

app/views/shared/_google_analytics.html.slim
script async="" src="https://www.googletagmanager.com/gtag/js?id=G-JKZ9M0N23J"
javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JKZ9M0N23J');

app/views/shared/_header.html.slim
.header
  .logo
    = link_to root_path do
      - if controller_name == 'results'
        = image_tag 'logos/logo-name-gray.png', class: 'logo-header'
      - else
        = image_tag 'logos/logo-name-white.png', class: 'logo-header'

app/views/shared/_privacy_policy.html.slim
h1.privacy-policy-title プライバシーポシリー
.privacy-policy-content
  p シマサガシ（以下，「当局」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。

  h2.privacy-policy-subtitle 第1条（個人情報）
  p「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報及び容貌，指紋，声紋にかかるデータ，及び健康保険証の保険者番号などの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。

  h2.privacy-policy-subtitle 第2条（個人情報の収集方法）
  p 当局は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を,当局の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。

  h2.privacy-policy-subtitle 第3条（個人情報を収集・利用する目的）
  p 当局が個人情報を収集・利用する目的は，以下のとおりです。
  ol
    li 当局サービスの提供・運営のため
    li ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
    li ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当局が提供する他のサービスの案内のメールを送付するため
    li メンテナンス，重要なお知らせなど必要に応じたご連絡のため
    li 利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
    li ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
    li 上記の利用目的に付随する目的

  h2.privacy-policy-subtitle 第4条（アクセス解析ツール）
  ol
    li 当サイトでは、Googleによるアクセス解析ツール「Googleアナリティクス」を使用しています。このGoogleアナリティクスはデータの収集のためにCookieを使用しています。
    li この機能はCookieを無効にすることで収集を拒否することが出来ますので、お使いのブラウザの設定をご確認ください。この規約に関しての詳細は#{ link_to 'Googleアナリティクスサービス利用規約', 'https://marketingplatform.google.com/about/analytics/terms/jp/', target: '_blank', rel: 'noopener noreferrer' }や#{ link_to 'Googleポリシーと規約', 'https://policies.google.com/technologies/ads?hl=ja', target: '_blank', rel: 'noopener noreferrer'}をご覧ください。

  h2.privacy-policy-subtitle 第5条（利用目的の変更）
  ol
    li 当局は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
    li 利用目的の変更を行った場合には，変更後の目的について，当局所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。

  h2.privacy-policy-subtitle 第6条（個人情報の第三者提供）
  ol
    li 当局は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。
    ol
      li 人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
      li 公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
      li 国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
      li 予め次の事項を告知あるいは公表し，かつ当局が個人情報保護委員会に届出をしたとき
      ol
        li 利用目的に第三者への提供を含むこと
        li 第三者に提供されるデータの項目
        li 第三者への提供の手段または方法
        li 本人の求めに応じて個人情報の第三者への提供を停止すること
        li 本人の求めを受け付ける方法
    li 前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
    ol
      li 当局が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
      li 合併その他の事由による事業の承継に伴って個人情報が提供される場合
      li 個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合

  h2.privacy-policy-subtitle 第7条（個人情報の開示）
  ol
    li 当局は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1件あたり1,000円の手数料を申し受けます。
    ol
      li 本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
      li 当局の業務の適正な実施に著しい支障を及ぼすおそれがある場合
      li その他法令に違反することとなる場合
    li 前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。

  h2.privacy-policy-subtitle 第8条（個人情報の訂正および削除）
  ol
    li ユーザーは，当局の保有する自己の個人情報が誤った情報である場合には，当局が定める手続きにより，当局に対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
    li 当局は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
    li 当局は，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。

  h2.privacy-policy-subtitle 第9条（個人情報の利用停止等）
  ol
    li 当局は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
    li 前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
    li 当局は，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
    li 前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。

  h2.privacy-policy-subtitle 第10条（プライバシーポリシーの変更）
  ol
    li 本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
    li 当局が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
  p.text-right
    | 以上